services:
  - type: web
    name: secure-auth-portal
    env: node
    plan: free
    buildCommand: npx prisma generate && DATABASE_URL=$DIRECT_URL npx prisma migrate deploy && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: AUTH_SECRET
        sync: false
      - key: AUTH_URL
        sync: false
      - key: EMAIL_SERVER_USER
        sync: false
      - key: EMAIL_SERVER_PASSWORD
        sync: false
      - key: EMAIL_SERVER_HOST
        value: "smtp.resend.com"
      - key: EMAIL_SERVER_PORT
        value: "465"
      - key: EMAIL_FROM
        sync: false
